## i learned markup to use obsidian

[ahhh so this  is how you write links](https://www.markdownguide.org/basic-syntax/ "link to markdown basic syntax")


In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
dataset = pd.read_csv('diabetes_data.csv')
dataset

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19   
1      Female  54.0             0              0         No Info  27.32   
2        Male  28.0             0              0           never  27.32   
3      Female  36.0             0              0         current  23.45   
4        Male  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0         No Info  27.32   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [3]:
X = dataset.iloc[:, 0:].values # specifying -1 leaves out one less column, not specifying means start from 0
y = dataset.iloc[:, -1].values

print(X[0])
print(dataset.columns)

['Female' 80.0 0 1 'never' 25.19 6.6 140 0]
Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')


In [4]:
pd.DataFrame(X, columns = ['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history','bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'])

gender   age hypertension heart_disease smoking_history    bmi  \
0      Female  80.0            0             1           never  25.19   
1      Female  54.0            0             0         No Info  27.32   
2        Male  28.0            0             0           never  27.32   
3      Female  36.0            0             0         current  23.45   
4        Male  76.0            1             1         current  20.14   
...       ...   ...          ...           ...             ...    ...   
99995  Female  80.0            0             0         No Info  27.32   
99996  Female   2.0            0             0         No Info  17.37   
99997    Male  66.0            0             0          former  27.83   
99998  Female  24.0            0             0           never  35.42   
99999  Female  57.0            0             0         current  22.43   

      HbA1c_level blood_glucose_level diabetes  
0             6.6                 140        0  
1             6.6                  80        0  
2             5.7                 158        0  
3             5.0                 155        0  
4             4.8                 155        0  
...           ...                 ...      ...  
99995         6.2                  90        0  
99996         6.5                 100        0  
99997         5.7                 155        0  
99998         4.0                 100        0  
99999         6.6                  90        0  

[100000 rows x 9 columns]

In [5]:
pd.DataFrame(y, columns= ["Diabetes"])

Diabetes
0             0
1             0
2             0
3             0
4             0
...         ...
99995         0
99996         0
99997         0
99998         0
99999         0

[100000 rows x 1 columns]

In [20]:
len(X[0])

110

In [14]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X[0])

[0.0 0.0 0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 'Female' 0 1 'never' 25.19
 6.6 140 0]


In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output=False), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)

[[0.0 0.0 0.0 ... 6.6 140 0]
 [0.0 0.0 0.0 ... 6.6 80 0]
 [0.0 0.0 0.0 ... 5.7 158 0]
 ...
 [0.0 0.0 0.0 ... 5.7 155 0]
 [0.0 0.0 0.0 ... 4.0 100 0]
 [0.0 0.0 0.0 ... 6.6 90 0]]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [29]:
X_test[0]

array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Female', 0,
       0, 'never', 27.32, 4.8, 140, 0], dtype=object)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) #error here
X_test = sc.transform(X_test)

In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
length = len(X_train[0])

# X_train = le.fit_transform(X_train)
# X_test = le.transform(X_test)

for i in range(length):
    X_train[: ,i] = le.fit_transform(X_train[: ,i])

length2 = len(X_test[0])
for i in range(length2):
    X_test[:,i] = le.fit_transform(X_test[:,i])

In [36]:
ann = tf.keras.models.Sequential()

#adding the input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [43]:
X_train = np.asarray(X_train).astype('float32')
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
2500/2500 [==============================] - 3s 1ms/step - loss: 6.3651e-06 - accuracy: 1.0000
Epoch 2/100
2500/2500 [==============================] - 3s 1ms/step - loss: 3.8492e-06 - accuracy: 1.0000
Epoch 3/100
2500/2500 [==============================] - 3s 1ms/step - loss: 0.0055 - accuracy: 0.9994
Epoch 4/100
2500/2500 [==============================] - 3s 1ms/step - loss: 2.6259e-06 - accuracy: 1.0000
Epoch 5/100
2500/2500 [==============================] - 3s 1ms/step - loss: 2.2514e-06 - accuracy: 1.0000
Epoch 6/100
2500/2500 [==============================] - 3s 1ms/step - loss: 2.1965e-06 - accuracy: 1.0000
Epoch 7/100
2500/2500 [==============================] - 3s 1ms/step - loss: 2.1325e-06 - accuracy: 1.0000
Epoch 8/100
2500/2500 [==============================] - 3s 1ms/step - loss: 1.9617e-06 - accuracy: 1.0000
Epoch 9/100
2500/2500 [==============================] - 3s 1ms/step - loss: 0.0012 - accuracy: 0.9998
Epoch 10/100
2500/2500 [=====================

KeyboardInterrupt: 

In [42]:
ann.build()
ann.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (32, 6)                   666       
                                                                 
 dense_4 (Dense)             (32, 6)                   42        
                                                                 
 dense_5 (Dense)             (32, 1)                   7         
                                                                 
Total params: 715 (2.79 KB)
Trainable params: 715 (2.79 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
