### this is my heading
hehehe

italics *is fun*
> block quots for denoting quotes

---

kewl

--- 

[ahhh so this  is how you write links](https://www.markdownguide.org/basic-syntax/ "link to markdown basic syntax")


In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [31]:
dataset = pd.read_csv('diabetes_data.csv')
dataset

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19   
1      Female  54.0             0              0         No Info  27.32   
2        Male  28.0             0              0           never  27.32   
3      Female  36.0             0              0         current  23.45   
4        Male  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0         No Info  27.32   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [37]:
X = dataset.iloc[:, 0:].values # specifying -1 leaves out one less column, not specifying means start from 0
y = dataset.iloc[:, -1].values

print(X[0])
print(dataset.columns)

['Female' 80.0 0 1 'never' 25.19 6.6 140 0]
Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')


In [38]:
pd.DataFrame(X, columns = ['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history','bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'])

gender   age hypertension heart_disease smoking_history    bmi  \
0      Female  80.0            0             1           never  25.19   
1      Female  54.0            0             0         No Info  27.32   
2        Male  28.0            0             0           never  27.32   
3      Female  36.0            0             0         current  23.45   
4        Male  76.0            1             1         current  20.14   
...       ...   ...          ...           ...             ...    ...   
99995  Female  80.0            0             0         No Info  27.32   
99996  Female   2.0            0             0         No Info  17.37   
99997    Male  66.0            0             0          former  27.83   
99998  Female  24.0            0             0           never  35.42   
99999  Female  57.0            0             0         current  22.43   

      HbA1c_level blood_glucose_level diabetes  
0             6.6                 140        0  
1             6.6                  80        0  
2             5.7                 158        0  
3             5.0                 155        0  
4             4.8                 155        0  
...           ...                 ...      ...  
99995         6.2                  90        0  
99996         6.5                 100        0  
99997         5.7                 155        0  
99998         4.0                 100        0  
99999         6.6                  90        0  

[100000 rows x 9 columns]

In [39]:
pd.DataFrame(y, columns= ["Diabetes"])

Diabetes
0             0
1             0
2             0
3             0
4             0
...         ...
99995         0
99996         0
99997         0
99998         0
99999         0

[100000 rows x 1 columns]

In [40]:
X

array([['Female', 80.0, 0, ..., 6.6, 140, 0],
       ['Female', 54.0, 0, ..., 6.6, 80, 0],
       ['Male', 28.0, 0, ..., 5.7, 158, 0],
       ...,
       ['Male', 66.0, 0, ..., 5.7, 155, 0],
       ['Female', 24.0, 0, ..., 4.0, 100, 0],
       ['Female', 57.0, 0, ..., 6.6, 90, 0]], dtype=object)

In [41]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [43]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[['Female' 80.0 0 ... 6.6 140 0]
 ['Female' 54.0 0 ... 6.6 80 0]
 ['Male' 28.0 0 ... 5.7 158 0]
 ...
 ['Male' 66.0 0 ... 5.7 155 0]
 ['Female' 24.0 0 ... 4.0 100 0]
 ['Female' 57.0 0 ... 6.6 90 0]]


In [49]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output=False), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)

[[1.0 0.0 1.0 ... 6.6 140 0]
 [1.0 0.0 1.0 ... 6.6 80 0]
 [1.0 0.0 1.0 ... 5.7 158 0]
 ...
 [1.0 0.0 1.0 ... 5.7 155 0]
 [1.0 0.0 1.0 ... 4.0 100 0]
 [1.0 0.0 1.0 ... 6.6 90 0]]


In [50]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [53]:
X_train[0]

array([1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       'Female', 0, 0, 'No Info', 16.45, 6.2, 159, 0], dtype=object)

In [52]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

ValueError: could not convert string to float: 'Female'